# Generated by Django 6.0.2 on 2026-09-15 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('points_cost', models.IntegerField(default=50)),
                ('stock', models.IntegerField(default=0)),
                ('icon', models.CharField(default='🎁', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('General Cleanup', 'General Cleanup'), ('Coastal Cleanup', 'Coastal Cleanup'), ('Tree Planting', 'Tree Planting'), ('River Cleanup', 'River Cleanup'), ('Waste Segregation', 'Waste Segregation'), ('Mangrove Planting', 'Mangrove Planting'), ('Urban Gardening', 'Urban Gardening')], default='General Cleanup', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PointAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='Direct award by official', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
